#!/usr/bin/env python3
"""
plotter_post.py  —  postprocesor G-code dla plotera 2D
=======================================================
Bierze gotowy G-code z Inkscape i filtruje go.
 
Użycie:
    python plotter_post.py rysunek.gcode
    python plotter_post.py rysunek.gcode --printer bambu
    python plotter_post.py rysunek.gcode --printer marlin
    python plotter_post.py rysunek.gcode --z-up 5 -o gotowy.gcode -v
 
"""
 
import re
import sys
import argparse
from pathlib import Path
 
 
Z_UP_DEFAULT    = 5.0
FEEDRATE_DRAW   = 3000
FEEDRATE_TRAVEL = 8000
FEEDRATE_Z      = 1000
 
 
RE_HEAT   = re.compile(r'^\s*M(104|109|140|190|141|116)\b', re.I)
RE_FAN    = re.compile(r'^\s*M(106|107)\b', re.I)
RE_G28    = re.compile(r'^\s*G28\b', re.I)
RE_E_ONLY = re.compile(r'^\s*[GT]\d+\s+E-?[\d.]+\s*(;.*)?$', re.I)
RE_E_AXIS = re.compile(r'\bE-?[\d.]+\s*', re.I)
RE_Z_MOVE = re.compile(r'^\s*(G[01])\b(.*?)\bZ\s*(-?[\d.]+)(.*?)$', re.I)
RE_F      = re.compile(r'\bF[\d.]+', re.I)
 
 
def pause_cmd(printer, msg):
    if printer == 'bambu':
        return f"M400 U1 ; {msg}"
    return f"M0 {msg}"
 
 
def start_sequence(z_up, printer):
    if printer == 'bambu':
        header = [
            "; generated by BambuStudio",
            "; HEADER_BLOCK_START",
            "; printer_model = Bambu Lab",
            "; nozzle_diameter = 0.4",
            "; bed_type = Textured PEI Plate",
            "; HEADER_BLOCK_END",
            "",
            "M104 S0",
            "M140 S0",
            "M107",
            "",
            "G21 ; mm",
            "G90 ; absolute positioning",
            "M83 ; relative extrusion",
            "G17 ; XY plane",
            "G94 ; feed per minute",
            "M220 S100",
            "M221 S100",
            "",
        ]
    else:
        header = [
            "; ╔══════════════════════════════════╗",
            "; ║  PLOTTER 2D — plotter_post.py    ║",
            "; ╚══════════════════════════════════╝",
            "",
            "M104 S0",
            "M140 S0",
            "M107",
            "",
            "G21 ; mm",
            "G90 ; absolute positioning",
            "G17 ; XY plane",
            "G94 ; feed per minute",
            "",
        ]
 
    return header + [
        "G28",
        "M420 S0",
        f"G0 Z{z_up:.2f} F{FEEDRATE_Z}",
        f"G0 X50 Y50 F{FEEDRATE_TRAVEL}",
        "",
        "; PAUZA — opusc Z az pisak dotknie papieru",
        pause_cmd(printer, "Ustaw Z i wznow z ekranu"),
        "",
        "G92 Z0",
        f"G0 Z{z_up:.2f} F{FEEDRATE_Z}",
        "",
        "; ─── START ──────────────────────────",
        "",
    ]
 
 
def end_sequence(z_up):
    return [
        "",
        "; ─── KONIEC ─────────────────────────",
        f"G0 Z{z_up:.2f} F{FEEDRATE_Z}",
        f"G0 X0 Y0 F{FEEDRATE_TRAVEL}",
        "M84",
    ]
 
 
def process_line(line, z_up):
    s = line.strip()
 
    if not s or s.startswith(';'):
        return line, None
 
    if RE_HEAT.match(s):
        return None, f"[rm] grzanie: {s[:60]}"
 
    if RE_FAN.match(s):
        return None, f"[rm] wentylator: {s[:60]}"
 
    if RE_G28.match(s):
        return None, f"[rm] G28: {s[:60]}"
 
    if RE_E_ONLY.match(s):
        return None, f"[rm] E-only: {s[:60]}"
 
    zm = RE_Z_MOVE.match(s)
    if zm:
        cmd   = zm.group(1).upper()
        pre   = RE_F.sub('', zm.group(2)).strip()
        z_val = float(zm.group(3))
        post  = RE_F.sub('', zm.group(4)).strip()
 
        if z_val <= z_up * 0.5:
            new_z, feed, cmt = 0.0, FEEDRATE_DRAW,    "; piszak W DOL"
        else:
            new_z, feed, cmt = z_up, FEEDRATE_TRAVEL, "; piszak w gore"
 
        parts = [cmd, f"Z{new_z:.2f}", f"F{feed}"]
        if pre:  parts.append(pre)
        if post: parts.append(post)
        parts.append(cmt)
        return ' '.join(parts), f"[Z] {z_val:.3f} → {new_z:.2f}"
 
    if RE_E_AXIS.search(s):
        return RE_E_AXIS.sub('', s).strip(), f"[rm E] {s[:60]}"
 
    return line, None
 
 
def process_file(inp, out, z_up, printer, verbose):
    raw = inp.read_text(encoding='utf-8', errors='replace').splitlines()
    result = []
    log = []
    removed = changed = kept = 0
 
    result.extend(start_sequence(z_up, printer))
 
    for i, line in enumerate(raw, 1):
        new_line, info = process_line(line, z_up)
        if info:
            log.append(f"  {i:5d}: {info}")
        if new_line is None:
            removed += 1
        else:
            if info: changed += 1
            else:    kept += 1
            result.append(new_line)
 
    result.extend(end_sequence(z_up))
    out.write_text('\n'.join(result) + '\n', encoding='utf-8')
 
    print(f"\n  wejście  : {inp}  ({len(raw)} linii)")
    print(f"  wyjście  : {out}  ({len(result)} linii)")
    print(f"  usunięto : {removed}  |  zmieniono : {changed}  |  zostawiono : {kept}\n")
 
    if verbose and log:
        print("─── log ─────────────────────────────────────")
        for entry in log: print(entry)
        print("─────────────────────────────────────────────\n")
 
 
def main():
    p = argparse.ArgumentParser(description="Postprocesor G-code Inkscape → plotter 2D")
    p.add_argument('input',      type=Path)
    p.add_argument('-o', '--output', type=Path, default=None)
    p.add_argument('--printer',  choices=['bambu', 'marlin'], default='bambu')
    p.add_argument('--z-up',     type=float, default=Z_UP_DEFAULT)
    p.add_argument('-v', '--verbose', action='store_true')
    args = p.parse_args()
 
    if not args.input.exists():
        print(f"Błąd: nie znaleziono {args.input}", file=sys.stderr)
        sys.exit(1)
 
    out = args.output or args.input.with_name(args.input.stem + '_plotter.gcode')
    process_file(args.input, out, args.z_up, args.printer, args.verbose)
 
 
if __name__ == '__main__':
    main()
 
# przykład:
# python plotter_post.py rysunek.gcode --printer bambu
# python plotter_post.py rysunek.gcode --printer marlin --z-up 3 -v